# # Lake Economy model engine reference
# 
# This folder contains a tested R prototype for the Lake Economy game engine.
# 
# Use `lake_economy_model_prototype.R` as the current mathematical reference for:
#   
#   - the six-entity Lake Economy setup
# - player offers / bid strengths
# - other-investor supply
# - issuer demand
# - equilibrium prices and capital quantities
# - lake health and local prosperity outcomes
# - frontier approximation
# 
# The R file is not a visual-design spec. It is a working prototype of the economic engine.
# 
# Important chart convention:
#   
#   - X-axis: expected outcome change
# - Y-axis: risk-adjusted return
# 
# The current R prototype may compute or plot a CE value / CE loss internally. That is fine for testing. For the website UI, convert this into a plain-language risk-adjusted return where higher is better if practical. If this conversion slows down the first prototype, keep the current internal calculation but label the UI carefully and do not reverse the axes.
# 
# For the first web prototype, it is acceptable to use the current parameter values while getting the interaction and visuals working. Parameter tuning can happen later.

# Lake Economy model prototype
# ------------------------------------------------------------
# Purpose:
#   A small non-marginal P/K-space equilibrium model for the Lake Economy game.
#   This is intended for parameter testing, not as final theory or production code.
#
# Core idea:
#   - The player sets offer weights across investable entities.
#   - Offers shift the player's capital-supply curve.
#   - The player's supply curve and other investors' aggregate supply curve combine
#     into an aggregate supply curve.
#   - Issuers/firms/organizations have an aggregate demand curve for capital.
#   - The economy clears in levels, producing equilibrium P and K.
#   - Outcomes are linear in equilibrium K.
#
# Notation in this script:
#   P: vector of equilibrium capital costs / required payoffs.
#   K: vector of equilibrium issuer capital.
#   b_share: player offer shares, nonnegative and summing to one.
#   s_player: player supply shifter generated by b_share.
#   E_player, E_other: quantity-form supply elasticities with respect to P.
#   PhiS: inverse aggregate supply slope, computed from E_player + E_other.
#   B: inverse demand slope matrix, where demand is P = a - B K.
#
# Equilibrium:
#   Player supply quantity:  K_player(P,b) = c_player + E_player P + s_player(b)
#   Other supply quantity:   K_other(P)   = c_other  + E_other P
#   Aggregate supply:        K_S(P,b)     = c_supply + E_total P + s_player(b)
#   Demand inverse curve:    P_D(K)       = a_demand - B K
#   Supply inverse curve:    P_S(K,b)     = PhiS [K - c_supply - s_player(b)]
#
#   Clearing P_S(K,b) = P_D(K):
#   K(b) = solve(PhiS + B, a_demand + PhiS %*% (c_supply + s_player(b)))
#   P(b) = a_demand - B %*% K(b)
#
# This model is intentionally simple. It preserves the key teaching distinction:
#   the player chooses offers, not final capital installed.

# -----------------------------
# Helpers
# -----------------------------

sym <- function(A) (A + t(A)) / 2

is_pos_def <- function(A, tol = 1e-9) {
  ev <- eigen(sym(A), symmetric = TRUE, only.values = TRUE)$values
  all(ev > tol)
}

condition_number <- function(A) {
  sv <- svd(A)$d
  max(sv) / min(sv)
}

normalize_precision <- function(Sigma) {
  P <- solve(Sigma)
  P / mean(diag(P))
}

random_simplex <- function(n, m) {
  X <- matrix(rexp(n * m), nrow = m, ncol = n)
  X / rowSums(X)
}

project_share <- function(x) {
  x <- pmax(as.numeric(x), 0)
  if (sum(x) <= 0) x[] <- 1
  x / sum(x)
}

named_vec <- function(values, names) {
  out <- as.numeric(values)
  names(out) <- names
  out
}

# -----------------------------
# Build one default lake economy
# -----------------------------

build_lake_params <- function(
    player_wealth = 100,
    other_wealth = 900,
    gamma_player = 8,
    gamma_other = 8,
    supply_scale = 0.045,
    offer_shift_scale = 18,
    player_baseline_share_of_K = 0.10,
    lake_outcome_weight = 0.50
) {
  entities <- c(
    "Scalable fish farm",
    "Steady fish farm",
    "Feed mill",
    "Hatchery",
    "Cold chain",
    "Lakefront industry"
  )
  n <- length(entities)

  # Visible firm/entity characteristics.
  # mu_business is not the equilibrium return. It is an operating/productivity signal
  # that can be shown to users as "expected business payoff".
  mu_business <- named_vec(c(0.145, 0.115, 0.130, 0.125, 0.105, 0.175), entities)
  sigma <- named_vec(c(0.28, 0.18, 0.20, 0.25, 0.16, 0.22), entities)

  # Baseline equilibrium scale and required payoff/cost of capital.
  # These are calibration anchors. Intercepts are chosen so that equal offers
  # reproduce this equilibrium.
  K0 <- named_vec(c(80, 60, 45, 35, 40, 70), entities)
  P0 <- named_vec(c(0.118, 0.098, 0.108, 0.112, 0.090, 0.142), entities)

  # Outcome intensities per unit of equilibrium capital.
  # These are deliberately stylized. Change freely.
  g_lake <- named_vec(c(0.25, 0.18, 0.02, 0.20, 0.08, -0.75), entities)
  g_prosperity <- named_vec(c(0.75, 0.52, 0.62, 0.45, 0.55, 0.38), entities)

  # Correlation matrix for payoff risk. Aquaculture entities are positively related.
  # Lakefront industry is less tied to aquaculture and slightly hedges some lake shocks.
  Corr <- matrix(c(
    1.00, 0.55, 0.45, 0.42, 0.35, -0.10,
    0.55, 1.00, 0.38, 0.35, 0.30, -0.05,
    0.45, 0.38, 1.00, 0.30, 0.50,  0.05,
    0.42, 0.35, 0.30, 1.00, 0.25, -0.02,
    0.35, 0.30, 0.50, 0.25, 1.00,  0.08,
   -0.10,-0.05, 0.05,-0.02, 0.08,  1.00
  ), nrow = n, byrow = TRUE)
  dimnames(Corr) <- list(entities, entities)
  Corr <- sym(Corr)
  if (!is_pos_def(Corr)) stop("Correlation matrix is not positive definite.")

  Sigma <- diag(sigma) %*% Corr %*% diag(sigma)
  dimnames(Sigma) <- list(entities, entities)

  # Other-investor participation / access weights.
  # Lower q means other investors are less willing/able to supply capital to that entity.
  # In quantity-supply form this lowers E_other. In inverse-slope form it raises the
  # implied supply slope for that direction.
  q_other <- named_vec(c(0.70, 0.95, 0.55, 0.45, 0.65, 1.00), entities)

  risk_precision <- normalize_precision(Sigma)

  E_player <- supply_scale * (player_wealth / gamma_player) * risk_precision
  E_other_base <- supply_scale * (other_wealth / gamma_other) * risk_precision
  Q <- diag(q_other, nrow = n)
  E_other <- Q %*% E_other_base %*% Q

  dimnames(E_player) <- list(entities, entities)
  dimnames(E_other) <- list(entities, entities)

  # Demand inverse slope matrix: P = a_demand - B K.
  # Positive diagonal: more own capital lowers marginal payoff/cost of capital.
  # Negative off-diagonal B_ij: capital in j raises demand/willingness to pay for i
  # (complementarity). Positive off-diagonal: substitution or damage.
  B <- matrix(0, n, n, dimnames = list(entities, entities))
  diag(B) <- c(0.0022, 0.0024, 0.0026, 0.0030, 0.0027, 0.0020)

  # Complementarities within aquaculture.
  B["Scalable fish farm", "Feed mill"] <- -0.00035
  B["Steady fish farm",   "Feed mill"] <- -0.00028
  B["Feed mill",          "Scalable fish farm"] <- -0.00018
  B["Feed mill",          "Steady fish farm"] <- -0.00012

  B["Scalable fish farm", "Hatchery"] <- -0.00025
  B["Steady fish farm",   "Hatchery"] <- -0.00020
  B["Hatchery",           "Scalable fish farm"] <- -0.00010
  B["Hatchery",           "Steady fish farm"] <- -0.00008

  B["Scalable fish farm", "Cold chain"] <- -0.00025
  B["Steady fish farm",   "Cold chain"] <- -0.00020
  B["Cold chain",         "Scalable fish farm"] <- -0.00015
  B["Cold chain",         "Steady fish farm"] <- -0.00010
  B["Feed mill",          "Cold chain"] <- -0.00012

  # Lakefront industry competes for lake capacity, labor, political attention, or water quality.
  B["Scalable fish farm", "Lakefront industry"] <-  0.00030
  B["Steady fish farm",   "Lakefront industry"] <-  0.00022
  B["Hatchery",           "Lakefront industry"] <-  0.00012
  B["Lakefront industry", "Scalable fish farm"] <-  0.00008
  B["Lakefront industry", "Steady fish farm"] <-  0.00006

  # Symmetrize lightly for numerical discipline. You can turn this off if you want
  # asymmetric economic links, but then check stability more carefully.
  B <- sym(B)

  if (!is_pos_def(B, tol = 1e-7)) {
    warning("Demand inverse slope B is not strongly positive definite. Adjust off-diagonal links.")
  }

  b0_share <- rep(1 / n, n)
  names(b0_share) <- entities

  make_offer_shift <- function(b_share) {
    b_share <- project_share(b_share)
    names(b_share) <- entities
    offer_shift_scale * (b_share - b0_share)
  }

  s0 <- make_offer_shift(b0_share)

  # Calibrate supply intercepts so that equal offers produce target K0 and P0.
  K_player0 <- player_baseline_share_of_K * K0
  K_other0 <- (1 - player_baseline_share_of_K) * K0

  c_player <- K_player0 - as.numeric(E_player %*% P0) - s0
  c_other <- K_other0 - as.numeric(E_other %*% P0)
  c_supply <- c_player + c_other

  names(c_player) <- entities
  names(c_other) <- entities
  names(c_supply) <- entities

  E_total <- E_player + E_other
  PhiS <- solve(E_total)
  dimnames(PhiS) <- list(entities, entities)

  # Calibrate inverse demand intercept so that equal offers produce target K0 and P0.
  a_demand <- P0 + as.numeric(B %*% K0)
  names(a_demand) <- entities

  params <- list(
    entities = entities,
    n = n,
    mu_business = mu_business,
    sigma = sigma,
    Corr = Corr,
    Sigma = Sigma,
    q_other = q_other,
    g_lake = g_lake,
    g_prosperity = g_prosperity,
    lake_outcome_weight = lake_outcome_weight,
    K0 = K0,
    P0 = P0,
    b0_share = b0_share,
    offer_shift_scale = offer_shift_scale,
    make_offer_shift = make_offer_shift,
    player_wealth = player_wealth,
    other_wealth = other_wealth,
    gamma_player = gamma_player,
    gamma_other = gamma_other,
    player_baseline_share_of_K = player_baseline_share_of_K,
    E_player = E_player,
    E_other = E_other,
    E_total = E_total,
    PhiS = PhiS,
    B = B,
    c_player = c_player,
    c_other = c_other,
    c_supply = c_supply,
    a_demand = a_demand
  )

  params
}

# -----------------------------
# Equilibrium solver
# -----------------------------

solve_lake_equilibrium <- function(b_share, params) {
  entities <- params$entities
  b_share <- project_share(b_share)
  names(b_share) <- entities

  s_player <- params$make_offer_shift(b_share)

  M <- params$PhiS + params$B
  rhs <- params$a_demand + as.numeric(params$PhiS %*% (params$c_supply + s_player))

  K <- as.numeric(solve(M, rhs))
  names(K) <- entities

  P <- params$a_demand - as.numeric(params$B %*% K)
  names(P) <- entities

  K_player <- params$c_player + as.numeric(params$E_player %*% P) + s_player
  K_other <- params$c_other + as.numeric(params$E_other %*% P)
  names(K_player) <- entities
  names(K_other) <- entities

  # Small numerical reconciliation.
  supply_gap <- K - (K_player + K_other)

  list(
    b_share = b_share,
    s_player = s_player,
    P = P,
    K = K,
    K_player = K_player,
    K_other = K_other,
    supply_gap = supply_gap
  )
}

compute_lake_metrics <- function(eq, params, lake_outcome_weight = params$lake_outcome_weight) {
  K <- eq$K
  K_player <- eq$K_player
  P <- eq$P

  lake <- sum(params$g_lake * K)
  prosperity <- sum(params$g_prosperity * K)
  blended <- lake_outcome_weight * lake + (1 - lake_outcome_weight) * prosperity

  player_expected_payoff <- sum(P * K_player)
  player_variance <- as.numeric(t(K_player) %*% params$Sigma %*% K_player)
  player_risk_penalty <- 0.5 * params$gamma_player / params$player_wealth * player_variance
  player_ce <- player_expected_payoff - player_risk_penalty

  list(
    lake = lake,
    prosperity = prosperity,
    blended = blended,
    player_expected_payoff = player_expected_payoff,
    player_variance = player_variance,
    player_risk_penalty = player_risk_penalty,
    player_ce = player_ce
  )
}

run_lake <- function(b_share, params, lake_outcome_weight = params$lake_outcome_weight) {
  eq <- solve_lake_equilibrium(b_share, params)
  metrics <- compute_lake_metrics(eq, params, lake_outcome_weight)
  c(eq, metrics = list(metrics))
}

# -----------------------------
# Preset offer vectors
# -----------------------------

make_presets <- function(params, lake_outcome_weight = params$lake_outcome_weight) {
  n <- params$n
  entities <- params$entities

  blended_g <- lake_outcome_weight * params$g_lake + (1 - lake_outcome_weight) * params$g_prosperity

  equal <- rep(1 / n, n)
  highest_payoff <- rep(0, n); highest_payoff[which.max(params$mu_business)] <- 1
  highest_raw_outcome <- rep(0, n); highest_raw_outcome[which.max(blended_g)] <- 1

  # A soft version of highest payoff/outcome can be easier for demos.
  softmax <- function(x, temp = 12) {
    z <- exp(temp * (x - max(x)))
    z / sum(z)
  }
  payoff_soft <- softmax(params$mu_business, temp = 25)
  outcome_soft <- softmax(blended_g, temp = 4)

  out <- list(
    equal_offers = equal,
    highest_business_payoff = highest_payoff,
    highest_raw_outcome = highest_raw_outcome,
    payoff_tilt_soft = payoff_soft,
    outcome_tilt_soft = outcome_soft
  )
  out <- lapply(out, function(x) { names(x) <- entities; x })
  out
}

# -----------------------------
# Frontier by grid search over feasible offer shares
# -----------------------------

frontier_grid <- function(params, lake_outcome_weight = params$lake_outcome_weight, n_grid = 10000, seed = 1) {
  set.seed(seed)
  entities <- params$entities
  n <- params$n

  presets <- make_presets(params, lake_outcome_weight)
  Bgrid <- random_simplex(n, n_grid)
  colnames(Bgrid) <- entities
  Bgrid <- rbind(
    do.call(rbind, presets),
    Bgrid
  )

  res <- vector("list", nrow(Bgrid))
  for (i in seq_len(nrow(Bgrid))) {
    eq <- solve_lake_equilibrium(Bgrid[i, ], params)
    m <- compute_lake_metrics(eq, params, lake_outcome_weight)
    res[[i]] <- c(
      as.list(Bgrid[i, ]),
      list(
        player_ce = m$player_ce,
        blended = m$blended,
        lake = m$lake,
        prosperity = m$prosperity,
        min_K = min(eq$K),
        min_K_player = min(eq$K_player),
        max_abs_supply_gap = max(abs(eq$supply_gap))
      )
    )
  }

  df <- as.data.frame(do.call(rbind, lapply(res, as.data.frame)))
  rownames(df) <- NULL

  # Add baseline-relative quantities using equal offers as baseline.
  base <- run_lake(presets$equal_offers, params, lake_outcome_weight)
  base_m <- base$metrics
  df$ce_loss_vs_equal <- base_m$player_ce - df$player_ce
  df$blended_gain_vs_equal <- df$blended - base_m$blended
  df$lake_gain_vs_equal <- df$lake - base_m$lake
  df$prosperity_gain_vs_equal <- df$prosperity - base_m$prosperity

  # Approximate efficient frontier: for each CE loss level, keep max outcome gain
  # among points with no larger CE loss. This is a constrained playable analogue
  # of an Impact Frontier.
  df <- df[order(df$ce_loss_vs_equal, -df$blended_gain_vs_equal), ]
  df$frontier_best_gain_up_to_loss <- cummax(df$blended_gain_vs_equal)
  df$is_frontier_point <- df$blended_gain_vs_equal >= df$frontier_best_gain_up_to_loss - 1e-10

  df
}

score_offer_against_grid <- function(b_share, params, lake_outcome_weight = params$lake_outcome_weight, grid = NULL) {
  if (is.null(grid)) grid <- frontier_grid(params, lake_outcome_weight, n_grid = 5000)

  current <- run_lake(b_share, params, lake_outcome_weight)
  base <- run_lake(params$b0_share, params, lake_outcome_weight)

  cur_gain <- current$metrics$blended - base$metrics$blended
  cur_loss <- base$metrics$player_ce - current$metrics$player_ce

  feasible <- grid[grid$ce_loss_vs_equal <= cur_loss + 1e-8, ]
  best_gain <- max(feasible$blended_gain_vs_equal, na.rm = TRUE)

  recovery <- if (best_gain > 0) cur_gain / best_gain else NA_real_

  list(
    current = current,
    baseline = base,
    ce_loss_vs_equal = cur_loss,
    blended_gain_vs_equal = cur_gain,
    best_gain_at_no_more_loss = best_gain,
    frontier_recovery = recovery
  )
}

# -----------------------------
# Diagnostics and display helpers
# -----------------------------

validate_lake_params <- function(params, verbose = TRUE) {
  checks <- list(
    Corr_pos_def = is_pos_def(params$Corr),
    Sigma_pos_def = is_pos_def(params$Sigma),
    B_pos_def = is_pos_def(params$B, tol = 1e-8),
    E_total_pos_def = is_pos_def(params$E_total, tol = 1e-8),
    PhiS_pos_def = is_pos_def(params$PhiS, tol = 1e-8),
    clearing_matrix_condition = condition_number(params$PhiS + params$B)
  )

  presets <- make_presets(params)
  preset_checks <- lapply(names(presets), function(nm) {
    eq <- solve_lake_equilibrium(presets[[nm]], params)
    c(
      min_K = min(eq$K),
      min_K_player = min(eq$K_player),
      min_K_other = min(eq$K_other),
      min_P = min(eq$P),
      max_abs_supply_gap = max(abs(eq$supply_gap))
    )
  })
  names(preset_checks) <- names(presets)

  if (verbose) {
    cat("\nMatrix checks\n")
    print(checks)
    cat("\nPreset equilibrium checks\n")
    print(do.call(rbind, preset_checks))
  }

  invisible(list(matrix_checks = checks, preset_checks = preset_checks))
}

entity_card_table <- function(params, lake_outcome_weight = params$lake_outcome_weight) {
  blended_g <- lake_outcome_weight * params$g_lake + (1 - lake_outcome_weight) * params$g_prosperity
  data.frame(
    entity = params$entities,
    current_size_K0 = as.numeric(params$K0),
    expected_business_payoff = as.numeric(params$mu_business),
    risk_sigma = as.numeric(params$sigma),
    lake_health_intensity = as.numeric(params$g_lake),
    local_prosperity_intensity = as.numeric(params$g_prosperity),
    blended_visible_intensity = as.numeric(blended_g),
    other_investor_access_q = as.numeric(params$q_other),
    row.names = NULL
  )
}

result_table <- function(run) {
  data.frame(
    entity = names(run$K),
    offer_share = as.numeric(run$b_share),
    supply_shift = as.numeric(run$s_player),
    P = as.numeric(run$P),
    K_total = as.numeric(run$K),
    K_player = as.numeric(run$K_player),
    K_other = as.numeric(run$K_other),
    row.names = NULL
  )
}

# -----------------------------
# Example run
# -----------------------------

params <- build_lake_params(lake_outcome_weight = 0.50)
validate_lake_params(params)

cat("\nVisible entity card table\n")
print(entity_card_table(params))

presets <- make_presets(params)

cat("\nPreset results\n")
for (nm in names(presets)) {
  run <- run_lake(presets[[nm]], params)
  cat("\n---", nm, "---\n")
  print(result_table(run))
  print(round(unlist(run$metrics), 4))
}

cat("\nBuilding approximate playable frontier grid...\n")
grid <- frontier_grid(params, n_grid = 5000, seed = 42)
cat("Number of approximate frontier points:", sum(grid$is_frontier_point), "\n")

# Score a preset against the approximate frontier.
score <- score_offer_against_grid(presets$highest_raw_outcome, params, grid = grid)
cat("\nHighest raw outcome preset scored against playable frontier\n")
print(round(c(
  ce_loss_vs_equal = score$ce_loss_vs_equal,
  blended_gain_vs_equal = score$blended_gain_vs_equal,
  best_gain_at_no_more_loss = score$best_gain_at_no_more_loss,
  frontier_recovery = score$frontier_recovery
), 4))

# Basic plot if running interactively.
if (interactive()) {
  plot(
    grid$blended_gain_vs_equal,
   -grid$ce_loss_vs_equal,
    pch = 16,
    cex = 0.35,
    ylab = "CE loss vs equal offers",
    xlab = "Blended outcome gain vs equal offers",
    main = "Approximate playable Impact Frontier"
  )
  points(
    grid$blended_gain_vs_equal[grid$is_frontier_point],
 -   grid$ce_loss_vs_equal[grid$is_frontier_point],
    pch = 16,
    cex = 0.6, col='green'
  )
}

